### ISSUE TITLE
CS 7036 Error Even without Base Class Inheritance

### ISSUE THREAD

**Issue by ramjet69** [conficient/BlazorTemplater#17]
Hello,

I am unable to figure out why I am getting a CS7036 on even the most basic model when using the Fluent Set.

**Here is my model:**
```cs
public class ConfirmUserEmailViewModel
{
    public string Name { get; set; }
    public string ConfirmUrl { get; set; }
}
````

**Here is my razor:**
```html
<p>Welcome @Model.Name,</p>
<p>Please confirm your email by <a href='@Model.ConfirmUrl'>clicking here</a>.</p>
<p>If you prefer you can copy and paste this link into your browser of choice.</p>
<br />
<p>@Model.ConfirmUrl</p>
<br />

@code {
    [Parameter] public ConfirmUserEmailViewModel Model { get; set; }
}
```

![image](https://user-images.githubusercontent.com/3164385/132956353-895f5c12-3c8c-4435-89af-e78301ccae81.png)

What am I doing wrong?

TIA

**Comment by conficient** [comment]
I've often made this mistake too myself! The setter syntax is `.Set(x => x.Property, Value)` - note the _comma_ not equals

So change your code to 
```cs
var viewResult = new ComponentRenderer<ConfirmUserEmail>()
   .Set(x => x.Model, viewModel)
  .Render();
```

That should do it

**Comment by conficient** [comment]
Just realised this was my error in my answer on your StackOverflow question - apologies for misleading you!

**Comment by ramjet69** [comment]
@conficient No Worries!

Thanks
