### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by dajma00** [conficient/BlazorTemplater#22]
In our Blazor components, we frequently use dependency injection using the @inject or [Inject] attributes in C# code. When creating an HTML string, we get the following error in the console:

```
Unhandled exception rendering component: Cannot provide a value for property 'AppState' on type 'Invoice2.Client.Pages.InvoiceView'. There is no registered service of type 'Invoice2.Shared.AppState'.
System.InvalidOperationException: Cannot provide a value for property 'AppState' on type 'Invoice2.Client.Pages.InvoiceView'. There is no registered service of type 'Invoice2.Shared.AppState'.

```
 Otherwise the component works just fine. Is there a way around this?

**Comment by conficient** [comment]
Did you add the service in the setup?
```c#
var appstate = new AppState(...);
var html = new ComponentRendered<InvoiceView>()
      .AddService<AppState>(appstate)
      .Render();
```

**Comment by conficient** [comment]
I should point out that the component renderer can't plug directly into your Dependency Injection container. If you're calling it from a Controller you should inject the instance you need in the Controller's constructor so it's present when you execute the action.

**Comment by conficient** [comment]
Closed - no update
