### ISSUE TITLE
Conditionals being lost in render

### ISSUE THREAD

**Issue by hopfrogpoe** [conficient/BlazorTemplater#34]
I'm trying to render a .razor file (email template) that contains conditionals like

```
<!--[if mso]>
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td width="50%" valign="top">
<![endif]-->
```
but they don't survive through the render. Is this something that can be fixed or is there a flag to set that already does this? Any help would be great.

**Comment by conficient** [comment]
It appears to be the default behaviour of the Blazor rendering engine. I found [this StackOverflow](https://stackoverflow.com/questions/67170227/blazor-conditional-html-comments) article which also suggests a workaround using `MarkupString`. Suggest you try this:
```
@((MarkupString)"<!--[if mso]-->")
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td width="50%" valign="top">
@((MarkupString)"<!--[endif]-->")
```
I'm adding a test for this to check this behaviour going forward.

**Comment by conficient** [comment]
All seems to work fine with the `MarkupString` workaround.

**Comment by hopfrogpoe** [comment]
Thank you for that! Not sure how I didn't find that in my searches but I appreciate it.
